import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores(['dist', 'src-tauri/target']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
  },
  {
    // shadcn-generated primitives co-locate CVA variant exports with their
    // component by convention (regenerated by the CLI, not hand-edited) —
    // exempt them from the fast-refresh single-export-per-file rule.
    files: ['src/components/ui/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  {
    // The three/ backdrop is a cohesive module: mood.tsx co-locates the
    // shared `mood` singleton and theme helpers with the MoodDriver component
    // that owns them. Splitting purely to satisfy fast-refresh would scatter
    // one concept across several files for no real benefit — exempt the dir.
    files: ['src/components/three/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
])
